export const GET_POPULAR_MOVIE = "GET_POPULAR_MOVIE";

export const GET_LOAD_MORE = "GET_LOAD_MORE";

export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL"

export const GET_MOVIE_CREW = "GET_MOVIE_CREW"

export const POST_FAVORITE_COUNT = "POST_FAVORITE_COUNT"

export const POST_FAVORITED = "POST_FAVORITED";

export const CHANGE_FAVORITE_COUNT_UP = "CHANGE_FAVORITE_COUNT_UP"

export const CHANGE_FAVORITE_COUNT_DOWN = "CHANGE_FAVORITE_COUNT_DOWN"

export const IS_FAVORITED = "IS_FAVORITED"
